### ISSUE TITLE
Build/Startup instructions

### ISSUE THREAD

**Issue by frankwallis** [rjbultitude/theconditionalorchestra#1]
Hi, this is cool project, I really like it!

I had a couple of issues getting it built so you may want to update the instructions in the readme:
- ```templates/index.js``` does not exist until you run ```gulp templates``` so the build failed initially until I figured it out
- I have never used php so I didn't know how to run the server, in the end I just renamed index.php -> index.html and that got it going but it's obviously not quite right

**Comment by rjbultitude** [comment]
Hi @frankwallis 

Thanks for the feedback and interest in the project :] 
I'll update the readme for sure. 

Regarding the php, I could (and should) rewrite it in node.js that way it would be easier to get started, but for now you could consider using [Mamp](https://www.mamp.info/en/)
